[package]
name = "pmls"
version = "1.2.0"
edition = "2024"

[[bin]]
name = "pmls"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
colored = "3"
rayon = "1.11.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
simd-json = "0.17"
which = "8.0.0"
