[package]
name = "pmls"
version = "1.0.1"
edition = "2024"

[[bin]]
name = "pmls"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
colored = "3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
simd-json = "0.17"
